Validators optionally log to wandb.
RusticLuftig/data-universe pull request #128
Opened 2024-01-14 04:51 UTC by Sid-Data-Universe

2024-01-14 04:57 UTC, RusticLuftig requested changes

2024-01-14 04:57 UTC, RusticLuftig commented on neurons/validator.py
> +                        self.new_wandb_run
Should this be a function call?

2024-01-14 05:00 UTC, Sid-Data-Universe commented on neurons/validator.py
> +                        self.new_wandb_run
Great catch!

2024-01-15 16:43 UTC, RusticLuftig approved these changes

2024-01-15 16:43 UTC, merged