Cache the compressed miner index.
RusticLuftig/data-universe pull request #200
Opened 2024-02-25 20:01 UTC by Sid-Data-Universe

Miners and Validators are restricted to using protocol 4. (Enforced on validator side with a minimum version to set weights as well). Confirmed in logs that no Miner is still returning an uncompressed index.

The Miner sqlite db is switched to use WAL over a journal. This removes the need to lock on reads.

The Miner now caches the compressed miner index response and refreshes that cache off the hot path.

2024-02-26 18:08 UTC, RusticLuftig requested changes
Overall LGTM. Just some nits

2024-02-26 18:08 UTC, RusticLuftig commented on storage/miner/sqlite_miner_storage.py
> +        # Force refresh index if 10 minutes beyond refersh period. Expected to be refreshed earlier by refresh loop.
nit: typo

2024-02-26 18:08 UTC, RusticLuftig commented on storage/miner/sqlite_miner_storage.py
> +                bt.logging.trace(f"Cached index within {time_delta} freshness period.")
nit: "Skipping updating cached index. It is already fresher than {time_delta}."

2024-02-26 22:41 UTC, Sid-Data-Universe commented on neurons/miner.py
> +            # Wait freshness period + 1 minute to try refreshing again.
Added.

2024-02-26 22:41 UTC, Sid-Data-Universe commented on storage/miner/sqlite_miner_storage.py
> +        # Force refresh index if 10 minutes beyond refersh period. Expected to be refreshed earlier by refresh loop.
fixed.

2024-02-26 22:41 UTC, Sid-Data-Universe commented on neurons/miner.py
> +            # Refresh the index if it hasn't been refreshed in the configured time period.
Great suggestion. Added.

2024-02-26 23:46 UTC, RusticLuftig requested changes

2024-02-26 23:46 UTC, RusticLuftig commented on storage/miner/sqlite_miner_storage.py
> +                    f"Skipping updating cached index. It is already fresher than {time_delta}."
Looks like you updated the wrong comment :(

2024-02-27 00:06 UTC, RusticLuftig approved these changes

2024-02-27 00:08 UTC, merged